apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app-sa
      containers:
        - name: app-container
          image: drawsmcgraw/tasky-alpine
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI 
              value: 'mongodb://admin:password@<ip>'
            - name: SECRET_KEY 
              value: 'doNotLoseThis'
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer