apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: drawsmcgraw/tasky
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI 
              value: 'mongodb://admin:superSecret@44.228.98.95:27017'
            - name: SECRET_KEY 
              value: 'doNotLoseThis'
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
